#!/bin/sh
# Docker-Clean-Images supportive script. Copyright (c) 2017, anselmos.github.com
# Originally found at : mugifly https://gist.github.com/mugifly/ffd3973d34c4a1b7c303cf024944a6f4
# Splitted into separated files

echo -e "\n\n-- Removing untagged images --\n"
docker rmi --force $(docker images | awk '/^<none>/ { print $3 }')
